# Generated by Django 5.1.2 on 2024-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_consultores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='consultores',
            field=models.CharField(choices=[('Marisa Rodrigues', 'Marisa Rodrigues'), ('Jacob Ambrósio', 'Jacob Ambrósio'), ('Vitor Leal', 'Vitor Leal'), ('Larissa Lari', 'Larissa Lari'), ('Thiago Gomes', 'Thiago Gomes')], default='-------------------', max_length=50),
        ),
    ]
